### ISSUE TITLE
vim todo

### ISSUE THREAD

**Issue by ih4cku** [ih4cku/blog#12]
- [x] `variable` and `option` difference
- [x] `let` and `set` difference

**Comment by ih4cku** [comment]
- [ ] to be familiar with ctags related function
  - http://stackoverflow.com/questions/1054701/get-ctags-in-vim-to-go-to-definition-not-declaration
  - http://stackoverflow.com/questions/563616/vim-and-ctags-tips-and-tricks
  - http://stackoverflow.com/questions/635770/jump-to-function-definition-in-vim
  - http://vi.stackexchange.com/questions/4955/how-to-jump-to-function-call
